### ISSUE TITLE
Attempting to find Photon OS 3.0 sources hangs forever

### ISSUE THREAD

**Issue by 0xDEC0DE** [juledwar/soufi#25]
VMWare appears to have shoved Photon OS 3.0 down the memory hole, and they are no longer providing repodata for it.  This confuses and angers `soufi`:

# Steps to reproduce

soufi photon filesystem 1.1.4.ph3

# Expected result

Empty result, file not found error, or similar

# Actual behavior

The command hangs indefinitely.

# Errata

Loading up the command in a debugger, it appears that the `urllib.error.HTTPError` exception that is raised in the child process cannot be serialized (due to an open `io.BufferedReader` object in it) and that causes it to pass nothing back to the caller, which then deadlocks, due to the lack of a read timeout on the queue.  Whoops.

These subprocesses have been observed taking multiple minutes to complete, so adding timeouts to the YumFinder IPC should be done with extreme care.

**Comment by juledwar** [comment]
Time for a new release.

**Comment by juledwar** [comment]
https://pypi.org/project/soufi/2022.3.14/
